#Recode by @UnrealYesus

# KALO FORK/CLONE USERNAME YG DI ATAS  G USH DI HAPUSS YAA KONTOLL

version: "3.9"

services:

  worker:

    build: .

    environment:


      API_ID: $API_ID

      API_HASH: $API_HASH

      BOT_TOKEN: $BOT_TOKEN
     
      DATABASE_URL: $DATABASE_URL

      ENVIRONMENT: $ENVIRONMENT
      
      MUST_JOIN: $MUST_JOIN
